version: 2
jobs:
  # Install dependencies
  build:
    docker:
      - image: circleci/node:10-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
          - dependencies-{{ .Environment.CACHE_VERSION }}-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

      - run: yarn lint
      - run: yarn ci:test
      - run: ./node_modules/.bin/ng build --configuration=production --aot
