version: 2
jobs:
  # Install dependencies
  setup:
    docker:
      - image: circleci/node:8-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  # Check lint
  lint:
    docker:
      - image: circleci/node:8-stretch-browsers

    steps:
      - run: yarn lint

  # Run unittest
  test:
    docker:
      - image: circleci/node:8-stretch-browsers

    steps:
      - run: yarn test
