version: 2
jobs:
  # Install dependencies
  build:
    docker:
      - image: circleci/node:8-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint
      - run: yarn test
      - run: ./node_modules/.bin/ng build --configuration=production --aot
